// exportBlueprint.js
// ---------------------------------------------------------------------------
// All export logic lives here, separate from the dashboard component.
//
// - buildMarkdown(): pure string builder, no dependencies.
// - downloadMarkdown(): triggers a .md file download from that string.
// - downloadPdf(): dynamically imports jsPDF (only when actually clicked,
//   so the ~200KB library never lands in the initial page bundle) and
//   builds a paginated, footer-stamped PDF using jsPDF's core text/line
//   APIs only — no jspdf-autotable or other extra packages.
//
// Section order in both exports matches the spec exactly:
// Startup Idea, Idea Analysis, Market Intelligence, Customer Persona,
// Product Planning, Tech Stack, Business Strategy, Cost Estimator,
// Revenue Simulator, Competitor Analysis, Go-To-Market Strategy,
// Launch Checklist, Investor Pitch, Startup Roadmap.
// ---------------------------------------------------------------------------

const COST_KEYS = ["domain", "hosting", "database", "aiApis", "email", "analytics", "storage", "authentication"];
const COST_LABELS = {
  domain: "Domain",
  hosting: "Hosting",
  database: "Database",
  aiApis: "AI APIs",
  email: "Email",
  analytics: "Analytics",
  storage: "Storage",
  authentication: "Authentication",
};

function ok(section) {
  return Boolean(section) && !section.error;
}
function okList(list) {
  return Array.isArray(list) && list.length > 0;
}
function formattedDate() {
  return new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });
}

export function safeTemplateStr(val) {
  if (!val) return "";
  if (typeof val === "string") return val;
  if (Array.isArray(val)) {
    return val.map((v) => (typeof v === "object" ? safeTemplateStr(v) : String(v))).join("\n\n");
  }
  if (typeof val === "object") {
    const subject = val.subject || val.subjectLine || val.headline || val.title;
    const body = val.body || val.emailBody || val.content || val.text || val.message || val.post;
    if (subject && body) return `Subject: ${subject}\n\n${body}`;
    if (body) return String(body);
    if (val.tweet || val.post) return String(val.tweet || val.post);
    return Object.entries(val).map(([k, v]) => `${k.toUpperCase()}:\n${typeof v === "object" ? JSON.stringify(v) : v}`).join("\n\n");
  }
  return String(val);
}

// ---------------------------------------------------------------------------
// Markdown export
// ---------------------------------------------------------------------------
export function buildMarkdown(blueprint, idea) {
  const {
    ideaAnalysis, viabilityScorecard, customerDiscovery, swotAnalysis,
    portersFiveForces, marketSizing, marketResearch, customerPersona, productPlan,
    technicalArchitecture, businessStrategy, pitch, roadmap,
    goToMarket, launchChecklist, costEstimator, revenueSimulator,
    competitorWeaknessAnalysis,
  } = blueprint;

  const L = [];
  const push = (s = "") => L.push(s);

  push(`# Startup Blueprint`);
  push();
  push(`_Generated by IdeaPulse AI on ${formattedDate()}_`);
  push();

  push(`## Startup Idea`);
  push();
  push(idea || "_Not provided._");
  push();

  push(`## Venture Viability Scorecard`);
  if (ok(viabilityScorecard)) {
    push(`**Composite Viability Score:** ${viabilityScorecard.score}/100`);
    push(`**Verdict:** ${viabilityScorecard.verdict}`);
    push(`**Executive Thesis:** ${viabilityScorecard.verdictReasoning}`);
    push(`**Sub-Scores:**`);
    push(`- Market Demand: ${viabilityScorecard.marketDemandScore}/100`);
    push(`- Technical Feasibility: ${viabilityScorecard.technicalFeasibilityScore}/100`);
    push(`- Monetization Engine: ${viabilityScorecard.monetizationScore}/100`);
    push();
    if (okList(viabilityScorecard.fatalRiskTraps)) {
      push(`**Fatal Risk Traps:**`);
      viabilityScorecard.fatalRiskTraps.forEach((trap) => push(`- ${trap}`));
      push();
    }
  } else push(`_Unavailable._`);
  push();

  push(`## Lean Customer Discovery ("Mom Test")`);
  if (ok(customerDiscovery)) {
    if (okList(customerDiscovery.interviewQuestions)) {
      push(`**Mom Test Interview Questions:**`);
      customerDiscovery.interviewQuestions.forEach((q, i) => push(`${i + 1}. ${q}`));
      push();
    }
    if (okList(customerDiscovery.redFlags)) {
      push(`**False-Positive Red Flags:**`);
      customerDiscovery.redFlags.forEach((rf) => push(`- ✕ ${rf}`));
      push();
    }
    if (okList(customerDiscovery.willingnessToPaySignals)) {
      push(`**Willingness-to-Pay Commitment Tests:**`);
      customerDiscovery.willingnessToPaySignals.forEach((wtp) => push(`- ✓ ${wtp}`));
      push();
    }
  } else push(`_Unavailable._`);
  push();

  push(`## Strategic Frameworks (SWOT & Porter's Five Forces)`);
  if (ok(swotAnalysis)) {
    push(`### SWOT (Strengths, Weaknesses, Opportunities, Threats) Matrix`);
    push(`**Strengths:**`);
    (swotAnalysis.strengths || []).forEach((s) => push(`- ${s}`));
    push(`**Weaknesses:**`);
    (swotAnalysis.weaknesses || []).forEach((w) => push(`- ${w}`));
    push(`**Opportunities:**`);
    (swotAnalysis.opportunities || []).forEach((o) => push(`- ${o}`));
    push(`**Threats:**`);
    (swotAnalysis.threats || []).forEach((t) => push(`- ${t}`));
    push();
  }
  if (ok(portersFiveForces)) {
    push(`### Porter's Five Forces Industry Analysis`);
    push(`- Buyer Bargaining Power: [${portersFiveForces.buyerPower?.level || "Moderate"}] ${portersFiveForces.buyerPower?.analysis || ""}`);
    push(`- Supplier Bargaining Power: [${portersFiveForces.supplierPower?.level || "Low"}] ${portersFiveForces.supplierPower?.analysis || ""}`);
    push(`- Competitive Rivalry: [${portersFiveForces.competitiveRivalry?.level || "Moderate"}] ${portersFiveForces.competitiveRivalry?.analysis || ""}`);
    push(`- Threat of Substitutes: [${portersFiveForces.threatOfSubstitutes?.level || "Moderate"}] ${portersFiveForces.threatOfSubstitutes?.analysis || ""}`);
    push(`- Threat of New Entrants: [${portersFiveForces.threatOfNewEntry?.level || "Moderate"}] ${portersFiveForces.threatOfNewEntry?.analysis || ""}`);
    push();
  }
  push();

  push(`## Market Sizing Architecture (TAM / SAM / SOM)`);
  if (ok(marketSizing)) {
    push(`- **TAM (Total Addressable Market):** ${marketSizing.tam?.value || "$14B"} — ${marketSizing.tam?.description || ""}`);
    push(`- **SAM (Serviceable Available Market):** ${marketSizing.sam?.value || "$2B"} — ${marketSizing.sam?.description || ""}`);
    push(`- **SOM (Serviceable Obtainable Market):** ${marketSizing.som?.value || "$40M"} — ${marketSizing.som?.description || ""}`);
  } else push(`_Unavailable._`);
  push();

  push(`## Idea Analysis`);
  if (ok(ideaAnalysis)) {
    push(`**Problem:** ${ideaAnalysis.problem}`);
    push();
    push(`**Goal:** ${ideaAnalysis.goal}`);
    push();
    push(`**Domain:** ${ideaAnalysis.domain}`);
    push();
    push(`**Feasibility:** ${ideaAnalysis.feasibility}`);
  } else push(`_Unavailable._`);
  push();

  push(`## Market Intelligence`);
  if (ok(marketResearch)) {
    push(`**Competitors:**`);
    (marketResearch.competitors || []).forEach((c) => push(`- ${c}`));
    push();
    push(`**Opportunities:**`);
    (marketResearch.opportunities || []).forEach((c) => push(`- ${c}`));
    push();
    push(`**Market Demand:** ${marketResearch.marketDemand}`);
  } else push(`_Unavailable._`);
  push();

  push(`## Customer Persona`);
  if (ok(customerPersona)) {
    push(`**Target Users:**`);
    (customerPersona.targetUsers || []).forEach((c) => push(`- ${c}`));
    push();
    push(`**Pain Points:**`);
    (customerPersona.painPoints || []).forEach((c) => push(`- ${c}`));
    push();
    push(`**User Profile:** ${customerPersona.userProfile}`);
  } else push(`_Unavailable._`);
  push();

  push(`## Product Planning`);
  if (ok(productPlan)) {
    push(`**MVP Features:**`);
    (productPlan.mvpFeatures || []).forEach((c) => push(`- ${c}`));
    push();
    push(`**Future Features:**`);
    (productPlan.futureFeatures || []).forEach((c) => push(`- ${c}`));
    push();
    push(`**Development Priority:** ${productPlan.developmentPriority}`);
  } else push(`_Unavailable._`);
  push();

  push(`## Tech Stack`);
  if (ok(technicalArchitecture)) {
    push(`| Layer | Recommendation |`);
    push(`|---|---|`);
    push(`| Frontend | ${technicalArchitecture.frontend} |`);
    push(`| Backend | ${technicalArchitecture.backend} |`);
    push(`| Database | ${technicalArchitecture.database} |`);
    push(`| Hosting | ${technicalArchitecture.hosting} |`);
    push(`| AI APIs | ${technicalArchitecture.aiApis} |`);
    push();
    push(`**Architecture Overview:** ${technicalArchitecture.architectureOverview}`);
  } else push(`_Unavailable._`);
  push();

  push(`## Business Strategy`);
  if (ok(businessStrategy)) {
    push(`**Revenue Model:** ${businessStrategy.revenueModel}`);
    push();
    push(`**Pricing Idea:** ${businessStrategy.pricingIdea}`);
    push();
    push(`**Marketing Channels:**`);
    (businessStrategy.marketingChannels || []).forEach((c) => push(`- ${c}`));
  } else push(`_Unavailable._`);
  push();

  push(`## Cost Estimator`);
  if (ok(costEstimator)) {
    push(`| Item | Monthly Cost | Free Tier OK | Note |`);
    push(`|---|---|---|---|`);
    COST_KEYS.forEach((k) => {
      const item = costEstimator[k];
      if (item) push(`| ${COST_LABELS[k]} | ${item.monthlyCost} | ${item.freeTierSufficient ? "Yes" : "No"} | ${item.note || ""} |`);
    });
    push();
    push(`**Estimated Monthly Total:** ${costEstimator.estimatedMonthlyCost}`);
    push();
    push(`**Estimated Yearly Total:** ${costEstimator.estimatedYearlyCost}`);
  } else push(`_Unavailable._`);
  push();

  push(`## Revenue Simulator`);
  if (ok(revenueSimulator)) {
    if (revenueSimulator.pricingAssumption) {
      push(`_Assumption: ${revenueSimulator.pricingAssumption}_`);
      push();
    }
    push(`| Users | Monthly Revenue | Annual Revenue |`);
    push(`|---|---|---|`);
    (revenueSimulator.projections || []).forEach((p) => {
      push(`| ${p.users} | ${p.monthlyRevenue} | ${p.annualRevenue} |`);
    });
  } else push(`_Unavailable._`);
  push();

  push(`## Competitor Analysis`);
  if (okList(competitorWeaknessAnalysis)) {
    competitorWeaknessAnalysis.forEach((c) => {
      push(`### ${c.competitor}`);
      push(`**Weaknesses:**`);
      (c.weaknesses || []).forEach((w) => push(`- ${w}`));
      push();
      push(`**Missed Opportunities:**`);
      (c.missedOpportunities || []).forEach((w) => push(`- ${w}`));
      push();
      push(`**Suggested Differentiation:** ${c.suggestedDifferentiation}`);
      push();
    });
  } else push(`_Unavailable._`);
  push();

  push(`## Go-To-Market Strategy`);
  if (ok(goToMarket)) {
    push(`**Target Audience:** ${goToMarket.targetAudience}`);
    push();
    push(`**Platforms:**`);
    (goToMarket.platforms || []).forEach((p) => push(`- **${p.name}** — ${p.why}`));
    push();
    push(`**LinkedIn Search Strategy:**`);
    (goToMarket.linkedInSearchStrategy || []).forEach((q) => push(`- ${q}`));
    push();
    const coldEmail = safeTemplateStr(goToMarket.coldEmailTemplate || goToMarket.coldEmail);
    const linkedInDm = safeTemplateStr(goToMarket.linkedInDmTemplate || goToMarket.linkedInDm);
    const redditPost = safeTemplateStr(goToMarket.redditLaunchPost || goToMarket.redditPost);
    const twitterPost = safeTemplateStr(goToMarket.twitterLaunchPost || goToMarket.twitterPost || goToMarket.xPost);

    if (coldEmail) {
      push(`**Cold Email Template:**`);
      push("```");
      push(coldEmail);
      push("```");
      push();
    }
    if (linkedInDm) {
      push(`**LinkedIn DM Template:**`);
      push("```");
      push(linkedInDm);
      push("```");
      push();
    }
    if (redditPost) {
      push(`**Reddit Launch Post:**`);
      push("```");
      push(redditPost);
      push("```");
      push();
    }
    if (twitterPost) {
      push(`**X (Twitter) Launch Post:**`);
      push("```");
      push(twitterPost);
      push("```");
      push();
    }
  } else push(`_Unavailable._`);
  push();

  push(`## Launch Checklist`);
  if (okList(launchChecklist)) {
    launchChecklist.forEach((item) => push(`- [ ] ${item}`));
  } else push(`_Unavailable._`);
  push();

  push(`## Investor Pitch`);
  if (ok(pitch)) {
    push(`**Elevator Pitch:** ${pitch.elevatorPitch}`);
    push();
    push(`**Executive Summary:** ${pitch.executiveSummary}`);
  } else push(`_Unavailable._`);
  push();

  push(`## Startup Roadmap`);
  if (ok(roadmap)) {
    (roadmap.milestones || []).forEach((m) => {
      push(`### ${m.week} — ${m.title}`);
      (m.tasks || []).forEach((t) => push(`- ${t}`));
      push();
    });
    push(`**Launch Plan:** ${roadmap.launchPlan}`);
  } else push(`_Unavailable._`);

  return L.join("\n");
}

export function downloadMarkdown(blueprint, idea) {
  const md = buildMarkdown(blueprint, idea);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "ideapulse-blueprint.md";
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

// ---------------------------------------------------------------------------
// PDF export — jsPDF is dynamically imported here, on demand, so it never
// adds weight to the app's initial load.
// ---------------------------------------------------------------------------
export async function downloadPdf(blueprint, idea) {
  const { jsPDF } = await import("jspdf");

  const {
    ideaAnalysis, viabilityScorecard, customerDiscovery, swotAnalysis,
    portersFiveForces, marketSizing, marketResearch, customerPersona, productPlan,
    technicalArchitecture, businessStrategy, pitch, roadmap,
    goToMarket, launchChecklist, costEstimator, revenueSimulator,
    competitorWeaknessAnalysis,
  } = blueprint;

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 44;
  const contentWidth = pageWidth - margin * 2;
  const footerZone = 40;
  let y = margin;

  const ensureSpace = (needed) => {
    if (y + needed > pageHeight - footerZone) {
      doc.addPage();
      y = margin;
    }
  };

  const heading = (text) => {
    ensureSpace(32);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.setTextColor(15, 23, 42);
    doc.text(text, margin, y);
    y += 22;
  };

  const subheading = (text) => {
    ensureSpace(20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10.5);
    doc.setTextColor(79, 70, 229);
    doc.text(text, margin, y);
    y += 15;
  };

  const paragraph = (text) => {
    if (!text) return;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(51, 65, 85);
    doc.splitTextToSize(text, contentWidth).forEach((line) => {
      ensureSpace(13);
      doc.text(line, margin, y);
      y += 13;
    });
    y += 6;
  };

  const bulletList = (items) => {
    if (!items?.length) return;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(51, 65, 85);
    items.forEach((item) => {
      doc.splitTextToSize(`•  ${item}`, contentWidth - 10).forEach((line) => {
        ensureSpace(13);
        doc.text(line, margin + 8, y);
        y += 13;
      });
    });
    y += 5;
  };

  const unavailable = () => {
    ensureSpace(18);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9.5);
    doc.setTextColor(180, 83, 9);
    doc.text("Generation unavailable.", margin, y);
    y += 20;
  };

  const divider = () => {
    ensureSpace(16);
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, y, pageWidth - margin, y);
    y += 16;
  };

  const ok = (s) => s && !s.error;
  const okList = (l) => Array.isArray(l) && l.length > 0;

  // -------------------------------------------------------------------------
  // Executive Cover Header Banner
  // -------------------------------------------------------------------------
  doc.setFillColor(15, 23, 42); // Slate-900 background banner
  doc.rect(0, 0, pageWidth, 68, "F");
  doc.setFillColor(99, 102, 241); // Indigo top accent stripe
  doc.rect(0, 0, pageWidth, 4, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text("IdeaPulse Executive Startup Blueprint", margin, 36);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(203, 213, 225);
  doc.text(`CONFIDENTIAL INVESTOR MEMO  |  SYNTHESIZED ON ${formattedDate().toUpperCase()}`, margin, 52);

  // Status Badge on Header Right
  doc.setFillColor(30, 41, 59);
  doc.roundedRect(pageWidth - margin - 130, 24, 130, 24, 4, 4, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(129, 140, 248);
  doc.text("12-AGENT AI CO-FOUNDER", pageWidth - margin - 65, 39, { align: "center" });

  y = 88;

  heading("Startup Concept & Objective");
  paragraph(idea || "Not provided.");
  divider();

  // -------------------------------------------------------------------------
  // Visual Chart 1: Viability Speedometer Gauge & Sub-Scores
  // -------------------------------------------------------------------------
  heading("Venture Viability Scorecard");
  if (ok(viabilityScorecard)) {
    ensureSpace(140);
    const score = Number(viabilityScorecard.score) || 75;
    const cardHeight = 110;

    // Card background
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(margin, y, contentWidth, cardHeight, 8, 8, "FD");

    // Left Score Box
    const scoreBoxWidth = 140;
    let scoreColor = [16, 185, 129]; // Emerald
    let badgeBg = [209, 250, 229];
    let badgeText = [6, 95, 70];
    if (score < 50) {
      scoreColor = [239, 68, 68];
      badgeBg = [254, 226, 226];
      badgeText = [153, 27, 27];
    } else if (score < 75) {
      scoreColor = [245, 158, 11];
      badgeBg = [254, 243, 199];
      badgeText = [146, 64, 14];
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(38);
    doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
    doc.text(String(score), margin + 24, y + 50);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(148, 163, 184);
    doc.text("/100", margin + 80, y + 42);

    // Overall Progress Bar under the big score
    doc.setFillColor(226, 232, 240);
    doc.roundedRect(margin + 20, y + 62, 100, 6, 3, 3, "F");
    doc.setFillColor(scoreColor[0], scoreColor[1], scoreColor[2]);
    doc.roundedRect(margin + 20, y + 62, Math.max(8, (score / 100) * 100), 6, 3, 3, "F");

    // Verdict Badge
    const verdict = (viabilityScorecard.verdict || "VIABLE").toUpperCase();
    doc.setFillColor(badgeBg[0], badgeBg[1], badgeBg[2]);
    doc.roundedRect(margin + 16, y + 78, scoreBoxWidth - 32, 18, 4, 4, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(badgeText[0], badgeText[1], badgeText[2]);
    doc.text(verdict, margin + scoreBoxWidth / 2, y + 90, { align: "center" });

    // Vertical separator
    doc.setDrawColor(226, 232, 240);
    doc.line(margin + scoreBoxWidth, y + 12, margin + scoreBoxWidth, y + cardHeight - 12);

    // Right side: 3 Sub-Score Metric Progress Bars
    const subX = margin + scoreBoxWidth + 18;
    const subWidth = contentWidth - scoreBoxWidth - 36;
    const subScores = [
      { label: "Market Demand", score: viabilityScorecard.marketDemandScore || 80, color: [59, 130, 246] },
      { label: "Technical Feasibility", score: viabilityScorecard.technicalFeasibilityScore || 85, color: [16, 185, 129] },
      { label: "Monetization Engine", score: viabilityScorecard.monetizationScore || 75, color: [245, 158, 11] },
    ];

    subScores.forEach((item, idx) => {
      const rowY = y + 26 + idx * 28;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(71, 85, 105);
      doc.text(item.label, subX, rowY);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      doc.text(`${item.score}%`, subX + subWidth, rowY, { align: "right" });

      // Track
      doc.setFillColor(226, 232, 240);
      doc.roundedRect(subX, rowY + 5, subWidth, 5, 2.5, 2.5, "F");
      // Fill
      doc.setFillColor(item.color[0], item.color[1], item.color[2]);
      doc.roundedRect(subX, rowY + 5, Math.max(6, (item.score / 100) * subWidth), 5, 2.5, 2.5, "F");
    });

    y += cardHeight + 14;

    // Executive Thesis
    if (viabilityScorecard.verdictReasoning) {
      subheading("Executive Investment Thesis");
      paragraph(viabilityScorecard.verdictReasoning);
    }

    // Fatal Risk Traps alert callout
    if (okList(viabilityScorecard.fatalRiskTraps)) {
      ensureSpace(50);
      doc.setFillColor(254, 242, 242);
      doc.setDrawColor(254, 202, 202);
      doc.roundedRect(margin, y, contentWidth, 22 + viabilityScorecard.fatalRiskTraps.length * 14, 6, 6, "FD");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(185, 28, 28);
      doc.text("FATAL RISK TRAPS & DEFENSE MECHANISMS", margin + 12, y + 15);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(127, 29, 29);
      viabilityScorecard.fatalRiskTraps.forEach((trap, i) => {
        doc.text(`!  ${trap}`, margin + 14, y + 30 + i * 14);
      });
      y += 30 + viabilityScorecard.fatalRiskTraps.length * 14 + 10;
    }
  } else unavailable();
  divider();

  // -------------------------------------------------------------------------
  // Visual Chart 2: TAM / SAM / SOM Market Sizing Architecture
  // -------------------------------------------------------------------------
  heading("Market Sizing Architecture (TAM / SAM / SOM)");
  if (ok(marketSizing)) {
    ensureSpace(120);
    const boxWidth = (contentWidth - 20) / 3;
    const boxHeight = 90;

    const cards = [
      {
        badge: "TAM",
        label: "Total Addressable Market",
        val: marketSizing.tam?.value || "$14B",
        desc: marketSizing.tam?.description || "Global macroeconomic ceiling",
        bg: [238, 242, 255],
        border: [199, 210, 254],
        primary: [67, 56, 202],
        secondary: [99, 102, 241],
      },
      {
        badge: "SAM",
        label: "Serviceable Available Market",
        val: marketSizing.sam?.value || "$2.4B",
        desc: marketSizing.sam?.description || "Addressable target segment",
        bg: [236, 253, 245],
        border: [167, 243, 208],
        primary: [6, 95, 70],
        secondary: [16, 185, 129],
      },
      {
        badge: "SOM",
        label: "Serviceable Obtainable Market",
        val: marketSizing.som?.value || "$48M",
        desc: marketSizing.som?.description || "Realistic 3-5 yr captured wedge",
        bg: [254, 243, 199],
        border: [253, 230, 138],
        primary: [146, 64, 14],
        secondary: [217, 119, 6],
      },
    ];

    cards.forEach((c, i) => {
      const bx = margin + i * (boxWidth + 10);
      doc.setFillColor(c.bg[0], c.bg[1], c.bg[2]);
      doc.setDrawColor(c.border[0], c.border[1], c.border[2]);
      doc.roundedRect(bx, y, boxWidth, boxHeight, 6, 6, "FD");

      // Badge
      doc.setFillColor(c.secondary[0], c.secondary[1], c.secondary[2]);
      doc.roundedRect(bx + 10, y + 10, 36, 14, 3, 3, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.setTextColor(255, 255, 255);
      doc.text(c.badge, bx + 28, y + 20, { align: "center" });

      // Value
      doc.setFont("helvetica", "bold");
      doc.setFontSize(18);
      doc.setTextColor(c.primary[0], c.primary[1], c.primary[2]);
      doc.text(c.val, bx + 10, y + 46);

      // Label
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(30, 41, 59);
      doc.text(c.label, bx + 10, y + 60);

      // Description
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(100, 116, 139);
      const splitDesc = doc.splitTextToSize(c.desc, boxWidth - 20);
      if (splitDesc[0]) doc.text(splitDesc[0], bx + 10, y + 74);
    });

    y += boxHeight + 14;
  } else unavailable();
  divider();

  // -------------------------------------------------------------------------
  // Customer Discovery & Mom Test Validation
  // -------------------------------------------------------------------------
  heading("Customer Discovery (Mom Test Protocol)");
  if (ok(customerDiscovery)) {
    if (okList(customerDiscovery.interviewQuestions)) {
      subheading("Mom Test Validation Questions (Avoid Pitching)");
      bulletList(customerDiscovery.interviewQuestions);
    }
    if (okList(customerDiscovery.redFlags)) {
      subheading("False-Positive Red Flags to Watch For");
      bulletList(customerDiscovery.redFlags);
    }
    if (okList(customerDiscovery.willingnessToPaySignals)) {
      subheading("Willingness-to-Pay Commitment Tests");
      bulletList(customerDiscovery.willingnessToPaySignals);
    }
  } else unavailable();
  divider();

  // -------------------------------------------------------------------------
  // Visual Chart 3: SWOT Analysis 2x2 Quadrant Grid
  // -------------------------------------------------------------------------
  heading("SWOT Strategic Matrix");
  if (ok(swotAnalysis)) {
    ensureSpace(190);
    const swotBoxWidth = (contentWidth - 10) / 2;
    const swotBoxHeight = 85;

    const quadrants = [
      {
        title: "STRENGTHS",
        items: (swotAnalysis.strengths || []).slice(0, 3),
        x: margin,
        y: y,
        bg: [240, 253, 244],
        border: [187, 247, 208],
        titleColor: [22, 101, 52],
      },
      {
        title: "WEAKNESSES",
        items: (swotAnalysis.weaknesses || []).slice(0, 3),
        x: margin + swotBoxWidth + 10,
        y: y,
        bg: [255, 241, 242],
        border: [254, 205, 211],
        titleColor: [159, 18, 57],
      },
      {
        title: "OPPORTUNITIES",
        items: (swotAnalysis.opportunities || []).slice(0, 3),
        x: margin,
        y: y + swotBoxHeight + 10,
        bg: [239, 246, 255],
        border: [191, 219, 254],
        titleColor: [30, 64, 175],
      },
      {
        title: "THREATS",
        items: (swotAnalysis.threats || []).slice(0, 3),
        x: margin + swotBoxWidth + 10,
        y: y + swotBoxHeight + 10,
        bg: [254, 252, 232],
        border: [254, 240, 138],
        titleColor: [133, 77, 14],
      },
    ];

    quadrants.forEach((q) => {
      doc.setFillColor(q.bg[0], q.bg[1], q.bg[2]);
      doc.setDrawColor(q.border[0], q.border[1], q.border[2]);
      doc.roundedRect(q.x, q.y, swotBoxWidth, swotBoxHeight, 6, 6, "FD");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(q.titleColor[0], q.titleColor[1], q.titleColor[2]);
      doc.text(q.title, q.x + 10, q.y + 16);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(51, 65, 85);
      q.items.forEach((item, idx) => {
        const itemLines = doc.splitTextToSize(`• ${item}`, swotBoxWidth - 20);
        if (itemLines[0]) {
          doc.text(itemLines[0], q.x + 10, q.y + 32 + idx * 16);
        }
      });
    });

    y += swotBoxHeight * 2 + 20;
  } else unavailable();
  divider();

  // -------------------------------------------------------------------------
  // Porter's Five Forces with Visual Badges
  // -------------------------------------------------------------------------
  if (ok(portersFiveForces)) {
    heading("Porter's Five Forces Analysis");
    const forces = [
      { name: "Buyer Bargaining Power", data: portersFiveForces.buyerPower },
      { name: "Supplier Bargaining Power", data: portersFiveForces.supplierPower },
      { name: "Competitive Rivalry", data: portersFiveForces.competitiveRivalry },
      { name: "Threat of Substitutes", data: portersFiveForces.threatOfSubstitutes },
      { name: "Threat of New Entrants", data: portersFiveForces.threatOfNewEntry },
    ];

    forces.forEach((f) => {
      const level = (f.data?.level || "Moderate").toUpperCase();
      let badgeBg = [254, 243, 199];
      let badgeText = [146, 64, 14];
      if (level === "HIGH") {
        badgeBg = [254, 226, 226];
        badgeText = [153, 27, 27];
      } else if (level === "LOW") {
        badgeBg = [209, 250, 229];
        badgeText = [6, 95, 70];
      }

      ensureSpace(28);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(30, 41, 59);
      doc.text(f.name, margin, y + 10);

      doc.setFillColor(badgeBg[0], badgeBg[1], badgeBg[2]);
      doc.roundedRect(pageWidth - margin - 80, y, 80, 15, 3, 3, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.setTextColor(badgeText[0], badgeText[1], badgeText[2]);
      doc.text(level, pageWidth - margin - 40, y + 11, { align: "center" });

      y += 18;
      paragraph(f.data?.analysis);
    });
    divider();
  } else unavailable();
  divider();

  heading("Idea Analysis");
  if (ok(ideaAnalysis)) {
    subheading("Problem"); paragraph(ideaAnalysis.problem);
    subheading("Goal"); paragraph(ideaAnalysis.goal);
    subheading("Domain"); paragraph(ideaAnalysis.domain);
    subheading("Feasibility"); paragraph(ideaAnalysis.feasibility);
  } else unavailable();
  divider();

  heading("Market Intelligence");
  if (ok(marketResearch)) {
    subheading("Competitors"); bulletList(marketResearch.competitors);
    subheading("Opportunities"); bulletList(marketResearch.opportunities);
    subheading("Market Demand"); paragraph(marketResearch.marketDemand);
  } else unavailable();
  divider();

  heading("Customer Persona");
  if (ok(customerPersona)) {
    subheading("Target Users"); bulletList(customerPersona.targetUsers);
    subheading("Pain Points"); bulletList(customerPersona.painPoints);
    subheading("User Profile"); paragraph(customerPersona.userProfile);
  } else unavailable();
  divider();

  heading("Product Planning");
  if (ok(productPlan)) {
    subheading("MVP Features"); bulletList(productPlan.mvpFeatures);
    subheading("Future Features"); bulletList(productPlan.futureFeatures);
    subheading("Development Priority"); paragraph(productPlan.developmentPriority);
  } else unavailable();
  divider();

  heading("Tech Stack");
  if (ok(technicalArchitecture)) {
    subheading("Frontend"); paragraph(technicalArchitecture.frontend);
    subheading("Backend"); paragraph(technicalArchitecture.backend);
    subheading("Database"); paragraph(technicalArchitecture.database);
    subheading("Hosting"); paragraph(technicalArchitecture.hosting);
    subheading("AI APIs"); paragraph(technicalArchitecture.aiApis);
    subheading("Architecture Overview"); paragraph(technicalArchitecture.architectureOverview);
  } else unavailable();
  divider();

  heading("Business Strategy");
  if (ok(businessStrategy)) {
    subheading("Revenue Model"); paragraph(businessStrategy.revenueModel);
    subheading("Pricing Idea"); paragraph(businessStrategy.pricingIdea);
    subheading("Marketing Channels"); bulletList(businessStrategy.marketingChannels);
  } else unavailable();
  divider();

  heading("Cost Estimator");
  if (ok(costEstimator)) {
    COST_KEYS.forEach((k) => {
      const item = costEstimator[k];
      if (item) {
        subheading(COST_LABELS[k]);
        paragraph(`${item.monthlyCost}${item.freeTierSufficient ? " (Free tier sufficient)" : ""} — ${item.note || ""}`);
      }
    });
    subheading("Totals");
    paragraph(`Monthly: ${costEstimator.estimatedMonthlyCost}   |   Yearly: ${costEstimator.estimatedYearlyCost}`);
  } else unavailable();
  divider();

  heading("Revenue Simulator");
  if (ok(revenueSimulator)) {
    if (revenueSimulator.pricingAssumption) {
      subheading("Pricing Assumption");
      paragraph(revenueSimulator.pricingAssumption);
    }
    subheading("Projections");
    (revenueSimulator.projections || []).forEach((p) => {
      paragraph(`${p.users} users  →  ${p.monthlyRevenue}/mo  (${p.annualRevenue}/yr)`);
    });
  } else unavailable();
  divider();

  heading("Competitor Analysis");
  if (okList(competitorWeaknessAnalysis)) {
    competitorWeaknessAnalysis.forEach((c) => {
      subheading(c.competitor);
      bulletList(c.weaknesses);
      bulletList(c.missedOpportunities);
      paragraph(c.suggestedDifferentiation);
    });
  } else unavailable();
  divider();

  heading("Go-To-Market Strategy");
  if (ok(goToMarket)) {
    subheading("Target Audience"); paragraph(goToMarket.targetAudience);
    subheading("Platforms");
    (goToMarket.platforms || []).forEach((p) => paragraph(`${p.name}: ${p.why}`));
    subheading("LinkedIn Search Strategy"); bulletList(goToMarket.linkedInSearchStrategy);
    subheading("Cold Email Template"); paragraph(safeTemplateStr(goToMarket.coldEmailTemplate || goToMarket.coldEmail));
    subheading("LinkedIn DM Template"); paragraph(safeTemplateStr(goToMarket.linkedInDmTemplate || goToMarket.linkedInDm));
    subheading("Reddit Launch Post"); paragraph(safeTemplateStr(goToMarket.redditLaunchPost || goToMarket.redditPost));
    subheading("X (Twitter) Launch Post"); paragraph(safeTemplateStr(goToMarket.twitterLaunchPost || goToMarket.twitterPost || goToMarket.xPost));
  } else unavailable();
  divider();

  heading("Launch Checklist");
  if (okList(launchChecklist)) bulletList(launchChecklist);
  else unavailable();
  divider();

  heading("Investor Pitch");
  if (ok(pitch)) {
    subheading("Elevator Pitch"); paragraph(pitch.elevatorPitch);
    subheading("Executive Summary"); paragraph(pitch.executiveSummary);
  } else unavailable();
  divider();

  heading("Startup Roadmap");
  if (ok(roadmap)) {
    (roadmap.milestones || []).forEach((m) => {
      subheading(`${m.week} — ${m.title}`);
      bulletList(m.tasks);
    });
    subheading("Launch Plan");
    paragraph(roadmap.launchPlan);
  } else unavailable();

  // Footer on every page
  const pageCount = doc.internal.getNumberOfPages();
  const generatedOn = formattedDate();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, pageHeight - footerZone + 8, pageWidth - margin, pageHeight - footerZone + 8);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text("IdeaPulse AI", margin, pageHeight - footerZone + 22);
    doc.text(`Generated on ${generatedOn}`, pageWidth - margin, pageHeight - footerZone + 22, { align: "right" });
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - footerZone + 22, { align: "center" });
  }

  doc.save("ideapulse-blueprint.pdf");
}