// exportBlueprint.js
// ---------------------------------------------------------------------------
// All export logic lives here, separate from the dashboard component.
//
// - buildMarkdown(): pure string builder, no dependencies.
// - downloadMarkdown(): triggers a .md file download from that string.
// - downloadPdf(): dynamically imports jsPDF (only when actually clicked,
//   so the ~200KB library never lands in the initial page bundle) and
//   builds a paginated, footer-stamped PDF using jsPDF's core text/line
//   APIs only — no jspdf-autotable or other extra packages.
//
// Section order in both exports matches the spec exactly:
// Startup Idea, Idea Analysis, Market Intelligence, Customer Persona,
// Product Planning, Tech Stack, Business Strategy, Cost Estimator,
// Revenue Simulator, Competitor Analysis, Go-To-Market Strategy,
// Launch Checklist, Investor Pitch, Startup Roadmap.
// ---------------------------------------------------------------------------

const COST_KEYS = ["domain", "hosting", "database", "aiApis", "email", "analytics", "storage", "authentication"];
const COST_LABELS = {
  domain: "Domain",
  hosting: "Hosting",
  database: "Database",
  aiApis: "AI APIs",
  email: "Email",
  analytics: "Analytics",
  storage: "Storage",
  authentication: "Authentication",
};

function ok(section) {
  return Boolean(section) && !section.error;
}
function okList(list) {
  return Array.isArray(list) && list.length > 0;
}
function formattedDate() {
  return new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });
}

// ---------------------------------------------------------------------------
// Markdown export
// ---------------------------------------------------------------------------
export function buildMarkdown(blueprint, idea) {
  const {
    ideaAnalysis, marketResearch, customerPersona, productPlan,
    technicalArchitecture, businessStrategy, pitch, roadmap,
    goToMarket, launchChecklist, costEstimator, revenueSimulator,
    competitorWeaknessAnalysis,
  } = blueprint;

  const L = [];
  const push = (s = "") => L.push(s);

  push(`# Startup Blueprint`);
  push();
  push(`_Generated by LaunchPilot AI on ${formattedDate()}_`);
  push();

  push(`## Startup Idea`);
  push();
  push(idea || "_Not provided._");
  push();

  push(`## Idea Analysis`);
  if (ok(ideaAnalysis)) {
    push(`**Problem:** ${ideaAnalysis.problem}`);
    push();
    push(`**Goal:** ${ideaAnalysis.goal}`);
    push();
    push(`**Domain:** ${ideaAnalysis.domain}`);
    push();
    push(`**Feasibility:** ${ideaAnalysis.feasibility}`);
  } else push(`_Unavailable._`);
  push();

  push(`## Market Intelligence`);
  if (ok(marketResearch)) {
    push(`**Competitors:**`);
    (marketResearch.competitors || []).forEach((c) => push(`- ${c}`));
    push();
    push(`**Opportunities:**`);
    (marketResearch.opportunities || []).forEach((c) => push(`- ${c}`));
    push();
    push(`**Market Demand:** ${marketResearch.marketDemand}`);
  } else push(`_Unavailable._`);
  push();

  push(`## Customer Persona`);
  if (ok(customerPersona)) {
    push(`**Target Users:**`);
    (customerPersona.targetUsers || []).forEach((c) => push(`- ${c}`));
    push();
    push(`**Pain Points:**`);
    (customerPersona.painPoints || []).forEach((c) => push(`- ${c}`));
    push();
    push(`**User Profile:** ${customerPersona.userProfile}`);
  } else push(`_Unavailable._`);
  push();

  push(`## Product Planning`);
  if (ok(productPlan)) {
    push(`**MVP Features:**`);
    (productPlan.mvpFeatures || []).forEach((c) => push(`- ${c}`));
    push();
    push(`**Future Features:**`);
    (productPlan.futureFeatures || []).forEach((c) => push(`- ${c}`));
    push();
    push(`**Development Priority:** ${productPlan.developmentPriority}`);
  } else push(`_Unavailable._`);
  push();

  push(`## Tech Stack`);
  if (ok(technicalArchitecture)) {
    push(`| Layer | Recommendation |`);
    push(`|---|---|`);
    push(`| Frontend | ${technicalArchitecture.frontend} |`);
    push(`| Backend | ${technicalArchitecture.backend} |`);
    push(`| Database | ${technicalArchitecture.database} |`);
    push(`| Hosting | ${technicalArchitecture.hosting} |`);
    push(`| AI APIs | ${technicalArchitecture.aiApis} |`);
    push();
    push(`**Architecture Overview:** ${technicalArchitecture.architectureOverview}`);
  } else push(`_Unavailable._`);
  push();

  push(`## Business Strategy`);
  if (ok(businessStrategy)) {
    push(`**Revenue Model:** ${businessStrategy.revenueModel}`);
    push();
    push(`**Pricing Idea:** ${businessStrategy.pricingIdea}`);
    push();
    push(`**Marketing Channels:**`);
    (businessStrategy.marketingChannels || []).forEach((c) => push(`- ${c}`));
  } else push(`_Unavailable._`);
  push();

  push(`## Cost Estimator`);
  if (ok(costEstimator)) {
    push(`| Item | Monthly Cost | Free Tier OK | Note |`);
    push(`|---|---|---|---|`);
    COST_KEYS.forEach((k) => {
      const item = costEstimator[k];
      if (item) push(`| ${COST_LABELS[k]} | ${item.monthlyCost} | ${item.freeTierSufficient ? "Yes" : "No"} | ${item.note || ""} |`);
    });
    push();
    push(`**Estimated Monthly Total:** ${costEstimator.estimatedMonthlyCost}`);
    push();
    push(`**Estimated Yearly Total:** ${costEstimator.estimatedYearlyCost}`);
  } else push(`_Unavailable._`);
  push();

  push(`## Revenue Simulator`);
  if (ok(revenueSimulator)) {
    if (revenueSimulator.pricingAssumption) {
      push(`_Assumption: ${revenueSimulator.pricingAssumption}_`);
      push();
    }
    push(`| Users | Monthly Revenue | Annual Revenue |`);
    push(`|---|---|---|`);
    (revenueSimulator.projections || []).forEach((p) => {
      push(`| ${p.users} | ${p.monthlyRevenue} | ${p.annualRevenue} |`);
    });
  } else push(`_Unavailable._`);
  push();

  push(`## Competitor Analysis`);
  if (okList(competitorWeaknessAnalysis)) {
    competitorWeaknessAnalysis.forEach((c) => {
      push(`### ${c.competitor}`);
      push(`**Weaknesses:**`);
      (c.weaknesses || []).forEach((w) => push(`- ${w}`));
      push();
      push(`**Missed Opportunities:**`);
      (c.missedOpportunities || []).forEach((w) => push(`- ${w}`));
      push();
      push(`**Suggested Differentiation:** ${c.suggestedDifferentiation}`);
      push();
    });
  } else push(`_Unavailable._`);
  push();

  push(`## Go-To-Market Strategy`);
  if (ok(goToMarket)) {
    push(`**Target Audience:** ${goToMarket.targetAudience}`);
    push();
    push(`**Platforms:**`);
    (goToMarket.platforms || []).forEach((p) => push(`- **${p.name}** — ${p.why}`));
    push();
    push(`**LinkedIn Search Strategy:**`);
    (goToMarket.linkedInSearchStrategy || []).forEach((q) => push(`- ${q}`));
    push();
    push(`**Cold Email Template:**`);
    push("```");
    push(goToMarket.coldEmailTemplate || "");
    push("```");
    push();
    push(`**LinkedIn DM Template:**`);
    push("```");
    push(goToMarket.linkedInDmTemplate || "");
    push("```");
    push();
    push(`**Reddit Launch Post:**`);
    push("```");
    push(goToMarket.redditLaunchPost || "");
    push("```");
    push();
    push(`**X (Twitter) Launch Post:**`);
    push("```");
    push(goToMarket.twitterLaunchPost || "");
    push("```");
  } else push(`_Unavailable._`);
  push();

  push(`## Launch Checklist`);
  if (okList(launchChecklist)) {
    launchChecklist.forEach((item) => push(`- [ ] ${item}`));
  } else push(`_Unavailable._`);
  push();

  push(`## Investor Pitch`);
  if (ok(pitch)) {
    push(`**Elevator Pitch:** ${pitch.elevatorPitch}`);
    push();
    push(`**Executive Summary:** ${pitch.executiveSummary}`);
  } else push(`_Unavailable._`);
  push();

  push(`## Startup Roadmap`);
  if (ok(roadmap)) {
    (roadmap.milestones || []).forEach((m) => {
      push(`### ${m.week} — ${m.title}`);
      (m.tasks || []).forEach((t) => push(`- ${t}`));
      push();
    });
    push(`**Launch Plan:** ${roadmap.launchPlan}`);
  } else push(`_Unavailable._`);

  return L.join("\n");
}

export function downloadMarkdown(blueprint, idea) {
  const md = buildMarkdown(blueprint, idea);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "launchpilot-blueprint.md";
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

// ---------------------------------------------------------------------------
// PDF export — jsPDF is dynamically imported here, on demand, so it never
// adds weight to the app's initial load.
// ---------------------------------------------------------------------------
export async function downloadPdf(blueprint, idea) {
  const { jsPDF } = await import("jspdf");

  const {
    ideaAnalysis, marketResearch, customerPersona, productPlan,
    technicalArchitecture, businessStrategy, pitch, roadmap,
    goToMarket, launchChecklist, costEstimator, revenueSimulator,
    competitorWeaknessAnalysis,
  } = blueprint;

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;
  const contentWidth = pageWidth - margin * 2;
  const footerZone = 40;
  let y = margin;

  const ensureSpace = (needed) => {
    if (y + needed > pageHeight - footerZone) {
      doc.addPage();
      y = margin;
    }
  };

  const heading = (text) => {
    ensureSpace(30);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(30, 41, 59);
    doc.text(text, margin, y);
    y += 24;
  };

  const subheading = (text) => {
    ensureSpace(18);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(79, 70, 229);
    doc.text(text, margin, y);
    y += 16;
  };

  const paragraph = (text) => {
    if (!text) return;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.splitTextToSize(text, contentWidth).forEach((line) => {
      ensureSpace(14);
      doc.text(line, margin, y);
      y += 14;
    });
    y += 6;
  };

  const bulletList = (items) => {
    if (!items?.length) return;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    items.forEach((item) => {
      doc.splitTextToSize(`•  ${item}`, contentWidth - 10).forEach((line) => {
        ensureSpace(14);
        doc.text(line, margin + 8, y);
        y += 14;
      });
    });
    y += 6;
  };

  const unavailable = () => {
    ensureSpace(18);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(180, 83, 9);
    doc.text("Generation unavailable.", margin, y);
    y += 22;
  };

  const divider = () => {
    ensureSpace(18);
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, y, pageWidth - margin, y);
    y += 18;
  };

  const ok = (s) => s && !s.error;
  const okList = (l) => Array.isArray(l) && l.length > 0;

  // Cover header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(15, 23, 42);
  doc.text("Startup Blueprint", margin, y);
  y += 28;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text("Prepared by LaunchPilot AI", margin, y);
  y += 30;

  heading("Startup Idea");
  paragraph(idea || "Not provided.");
  divider();

  heading("Idea Analysis");
  if (ok(ideaAnalysis)) {
    subheading("Problem"); paragraph(ideaAnalysis.problem);
    subheading("Goal"); paragraph(ideaAnalysis.goal);
    subheading("Domain"); paragraph(ideaAnalysis.domain);
    subheading("Feasibility"); paragraph(ideaAnalysis.feasibility);
  } else unavailable();
  divider();

  heading("Market Intelligence");
  if (ok(marketResearch)) {
    subheading("Competitors"); bulletList(marketResearch.competitors);
    subheading("Opportunities"); bulletList(marketResearch.opportunities);
    subheading("Market Demand"); paragraph(marketResearch.marketDemand);
  } else unavailable();
  divider();

  heading("Customer Persona");
  if (ok(customerPersona)) {
    subheading("Target Users"); bulletList(customerPersona.targetUsers);
    subheading("Pain Points"); bulletList(customerPersona.painPoints);
    subheading("User Profile"); paragraph(customerPersona.userProfile);
  } else unavailable();
  divider();

  heading("Product Planning");
  if (ok(productPlan)) {
    subheading("MVP Features"); bulletList(productPlan.mvpFeatures);
    subheading("Future Features"); bulletList(productPlan.futureFeatures);
    subheading("Development Priority"); paragraph(productPlan.developmentPriority);
  } else unavailable();
  divider();

  heading("Tech Stack");
  if (ok(technicalArchitecture)) {
    subheading("Frontend"); paragraph(technicalArchitecture.frontend);
    subheading("Backend"); paragraph(technicalArchitecture.backend);
    subheading("Database"); paragraph(technicalArchitecture.database);
    subheading("Hosting"); paragraph(technicalArchitecture.hosting);
    subheading("AI APIs"); paragraph(technicalArchitecture.aiApis);
    subheading("Architecture Overview"); paragraph(technicalArchitecture.architectureOverview);
  } else unavailable();
  divider();

  heading("Business Strategy");
  if (ok(businessStrategy)) {
    subheading("Revenue Model"); paragraph(businessStrategy.revenueModel);
    subheading("Pricing Idea"); paragraph(businessStrategy.pricingIdea);
    subheading("Marketing Channels"); bulletList(businessStrategy.marketingChannels);
  } else unavailable();
  divider();

  heading("Cost Estimator");
  if (ok(costEstimator)) {
    COST_KEYS.forEach((k) => {
      const item = costEstimator[k];
      if (item) {
        subheading(COST_LABELS[k]);
        paragraph(`${item.monthlyCost}${item.freeTierSufficient ? " (Free tier sufficient)" : ""} — ${item.note || ""}`);
      }
    });
    subheading("Totals");
    paragraph(`Monthly: ${costEstimator.estimatedMonthlyCost}   |   Yearly: ${costEstimator.estimatedYearlyCost}`);
  } else unavailable();
  divider();

  heading("Revenue Simulator");
  if (ok(revenueSimulator)) {
    if (revenueSimulator.pricingAssumption) {
      subheading("Pricing Assumption");
      paragraph(revenueSimulator.pricingAssumption);
    }
    subheading("Projections");
    (revenueSimulator.projections || []).forEach((p) => {
      paragraph(`${p.users} users  →  ${p.monthlyRevenue}/mo  (${p.annualRevenue}/yr)`);
    });
  } else unavailable();
  divider();

  heading("Competitor Analysis");
  if (okList(competitorWeaknessAnalysis)) {
    competitorWeaknessAnalysis.forEach((c) => {
      subheading(c.competitor);
      bulletList(c.weaknesses);
      bulletList(c.missedOpportunities);
      paragraph(c.suggestedDifferentiation);
    });
  } else unavailable();
  divider();

  heading("Go-To-Market Strategy");
  if (ok(goToMarket)) {
    subheading("Target Audience"); paragraph(goToMarket.targetAudience);
    subheading("Platforms");
    (goToMarket.platforms || []).forEach((p) => paragraph(`${p.name}: ${p.why}`));
    subheading("LinkedIn Search Strategy"); bulletList(goToMarket.linkedInSearchStrategy);
    subheading("Cold Email Template"); paragraph(goToMarket.coldEmailTemplate);
    subheading("LinkedIn DM Template"); paragraph(goToMarket.linkedInDmTemplate);
    subheading("Reddit Launch Post"); paragraph(goToMarket.redditLaunchPost);
    subheading("X (Twitter) Launch Post"); paragraph(goToMarket.twitterLaunchPost);
  } else unavailable();
  divider();

  heading("Launch Checklist");
  if (okList(launchChecklist)) bulletList(launchChecklist);
  else unavailable();
  divider();

  heading("Investor Pitch");
  if (ok(pitch)) {
    subheading("Elevator Pitch"); paragraph(pitch.elevatorPitch);
    subheading("Executive Summary"); paragraph(pitch.executiveSummary);
  } else unavailable();
  divider();

  heading("Startup Roadmap");
  if (ok(roadmap)) {
    (roadmap.milestones || []).forEach((m) => {
      subheading(`${m.week} — ${m.title}`);
      bulletList(m.tasks);
    });
    subheading("Launch Plan");
    paragraph(roadmap.launchPlan);
  } else unavailable();

  // Footer on every page
  const pageCount = doc.internal.getNumberOfPages();
  const generatedOn = formattedDate();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, pageHeight - footerZone + 8, pageWidth - margin, pageHeight - footerZone + 8);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text("LaunchPilot AI", margin, pageHeight - footerZone + 22);
    doc.text(`Generated on ${generatedOn}`, pageWidth - margin, pageHeight - footerZone + 22, { align: "right" });
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - footerZone + 22, { align: "center" });
  }

  doc.save("launchpilot-blueprint.pdf");
}